canonifyURLs = true
cleanDestinationDir = true
copyright = 'Â© 2024 Copyright warashi'
defaultContentLanguage = 'ja'
enableEmoji = true
enableGitInfo = false
enableInlineShortcodes = true
hasCJKLanguage = true
languageCode = 'ja-JP'
timeZone = 'Asia/Tokyo'
title = '#times-warashi'
sectionPagesMenu = 'main'
